name: Portfolio CI

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Railway if event branch is main
    
    if: github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    
    steps:
    - name: checkout Repo
      uses: actions/checkout@v2.4.2
      with:
        ref: main
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
    - name: Install Railway CLI
      run: |
        npm i -g @railway/cli
    - name: Deploy to Railway
      run: |
        RAILWAY_TOKEN=$RAILWAY_TOKEN railway up
